version: '3'

services:
  report-app:
    image: registry.smartsignal.co.kr/report-app:latest
    restart: always
    networks:
      - traefik
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3000
      - API_URI=${API_URI}
      - KAKAO_KEY=${REACT_APP_FIREBASE_API_KEY}
      - TZ=Asia/Seoul
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.report.rule=Host(`report.stl1.co.kr`)"
      - "traefik.http.routers.report.entrypoints=websecure"
      - "traefik.http.routers.report.tls.certresolver=resolver"
      - "traefik.http.services.report.loadbalancer.server.port=3000"
      - "traefik.http.services.report.loadbalancer.server.scheme=http"

networks:
  traefik:
    external: true
